version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
      
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
